line-length = 89

# Exclude some directories:
exclude = [
  ".git",
  "__pycache__",
  "migrations",
  ".venv",
  "settings.py"
]

[lint]
preview = true
select = ["E", "F", "I", "C90"]

[lint.extend-per-file-ignores]
"__init__.py" = ["F401"]
"config/*.py manage.py" = ["S104"]
".//contributors/**" = ["E501"]
