from contributors.views import (
    config,
    contributor,
    contributors,
    contributors_for_month,
    home,
    issues,
    organization,
    organizations,
    project,
    projects,
    repositories,
    repository,
    webhook,
)
