# Generated by Django 2.2.5 on 2019-09-30 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191001_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='avatar_url',
            field=models.URLField(default='NA'),
            preserve_default=False,
        ),
    ]
