# Generated by Django 2.2.8 on 2019-12-23 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('cit', 'commit'), ('iss', 'issue'), ('pr', 'pull request'), ('cnt', 'comment')], max_length=3, verbose_name='type')),
                ('html_url', models.URLField(verbose_name='URL')),
                ('created_at', models.DateTimeField(verbose_name='creation date')),
            ],
            options={
                'verbose_name': 'contribution',
                'verbose_name_plural': 'contributions',
            },
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='name')),
                ('html_url', models.URLField(verbose_name='URL')),
                ('is_tracked', models.BooleanField(default=True, verbose_name='tracked')),
                ('login', models.CharField(max_length=50, verbose_name='login')),
                ('avatar_url', models.URLField(verbose_name='avatar URL')),
                ('is_visible', models.BooleanField(default=True, verbose_name='visible')),
            ],
            options={
                'verbose_name': 'contributor',
                'verbose_name_plural': 'contributors',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='name')),
                ('html_url', models.URLField(verbose_name='URL')),
                ('is_tracked', models.BooleanField(default=True, verbose_name='tracked')),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='name')),
                ('html_url', models.URLField(verbose_name='URL')),
                ('is_tracked', models.BooleanField(default=True, verbose_name='tracked')),
                ('full_name', models.CharField(max_length=50, verbose_name='full name')),
                ('is_visible', models.BooleanField(default=True, verbose_name='visible')),
                ('contributors', models.ManyToManyField(through='contributors.Contribution', to='contributors.Contributor', verbose_name='contributors')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contributors.Organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'repository',
                'verbose_name_plural': 'repositories',
            },
        ),
        migrations.AddField(
            model_name='contribution',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contributors.Contributor', verbose_name='contributor'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contributors.Repository', verbose_name='repository'),
        ),
        migrations.CreateModel(
            name='CommitStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additions', models.IntegerField(default=0, verbose_name='additions')),
                ('deletions', models.IntegerField(default=0, verbose_name='deletions')),
                ('commit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='contributors.Contribution', verbose_name='commit')),
            ],
            options={
                'verbose_name': 'commit stats',
                'verbose_name_plural': 'commit stats',
            },
        ),
    ]
