# Generated by Django 2.2.6 on 2019-10-18 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commits', models.IntegerField(default=0, verbose_name='commits')),
                ('additions', models.IntegerField(default=0, verbose_name='additions')),
                ('deletions', models.IntegerField(default=0, verbose_name='deletions')),
                ('pull_requests', models.IntegerField(default=0, verbose_name='pull requests')),
                ('issues', models.IntegerField(default=0, verbose_name='issues')),
                ('comments', models.IntegerField(default=0, verbose_name='comments')),
            ],
            options={
                'verbose_name': 'Contribution',
                'verbose_name_plural': 'Contributions',
            },
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='name')),
                ('html_url', models.URLField(verbose_name='html url')),
                ('login', models.CharField(max_length=30, verbose_name='Login')),
                ('avatar_url', models.URLField(verbose_name='avatar url')),
            ],
            options={
                'verbose_name': 'Contributor',
                'verbose_name_plural': 'Contributors',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='name')),
                ('html_url', models.URLField(verbose_name='html url')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='name')),
                ('html_url', models.URLField(verbose_name='html url')),
                ('full_name', models.CharField(max_length=30, verbose_name='full name')),
                ('contributors', models.ManyToManyField(through='contributors.Contribution', to='contributors.Contributor', verbose_name='Contributors')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contributors.Organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Repository',
                'verbose_name_plural': 'Repositories',
            },
        ),
        migrations.AddField(
            model_name='contribution',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contributors.Contributor', verbose_name='Contributor'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contributors.Repository', verbose_name='Repository'),
        ),
    ]
