# Generated by Django 2.2.8 on 2020-02-07 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('is_open', models.BooleanField(verbose_name='open')),
                ('issue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contributors.Contribution', verbose_name='issue')),
            ],
            options={
                'verbose_name': 'issue info',
                'verbose_name_plural': 'issue info',
            },
        ),
    ]
