# Generated by Django 2.2.6 on 2019-11-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='login',
            field=models.CharField(max_length=40, verbose_name='Login'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='name',
            field=models.CharField(max_length=40, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=40, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='full_name',
            field=models.CharField(max_length=40, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='name',
            field=models.CharField(max_length=40, null=True, verbose_name='name'),
        ),
    ]
