# Generated by Django 2.2.11 on 2020-04-02 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0002_issueinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='name')),
                ('html_url', models.URLField(verbose_name='URL')),
                ('is_tracked', models.BooleanField(default=True, verbose_name='tracked')),
                ('full_name', models.CharField(max_length=50, verbose_name='full name')),
                ('is_visible', models.BooleanField(default=True, verbose_name='visible')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
            },
        ),
        migrations.AlterField(
            model_name='issueinfo',
            name='issue',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='contributors.Contribution', verbose_name='issue'),
        ),
    ]
