# Generated by Django 2.2.11 on 2020-04-03 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0003_auto_20200403_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contributors.Project', verbose_name='project'),
        ),
    ]
