# Generated by Django 2.2.8 on 2019-12-06 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0003_auto_20191201_2222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contribution',
            options={'verbose_name': 'contribution', 'verbose_name_plural': 'contributions'},
        ),
        migrations.AlterModelOptions(
            name='contributor',
            options={'verbose_name': 'contributor', 'verbose_name_plural': 'contributors'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'organization', 'verbose_name_plural': 'organizations'},
        ),
        migrations.AlterModelOptions(
            name='repository',
            options={'verbose_name': 'repository', 'verbose_name_plural': 'repositories'},
        ),
        migrations.AddField(
            model_name='contributor',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='visible'),
        ),
        migrations.AddField(
            model_name='repository',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='visible'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contributors.Contributor', verbose_name='contributor'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contributors.Repository', verbose_name='repository'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='avatar_url',
            field=models.URLField(verbose_name='avatar URL'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='html_url',
            field=models.URLField(verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='login',
            field=models.CharField(max_length=50, verbose_name='login'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='html_url',
            field=models.URLField(verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='contributors',
            field=models.ManyToManyField(through='contributors.Contribution', to='contributors.Contributor', verbose_name='contributors'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='full_name',
            field=models.CharField(max_length=50, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='html_url',
            field=models.URLField(verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contributors.Organization', verbose_name='organization'),
        ),
    ]
