# Generated by Django 3.1.6 on 2021-10-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0005_auto_20200710_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='repository',
            name='labels',
            field=models.ManyToManyField(to='contributors.Label', verbose_name='labels'),
        ),
    ]
