# Generated by Django 3.2.5 on 2022-07-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0006_auto_20211016_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issueinfo',
            name='is_open',
        ),
        migrations.AddField(
            model_name='issueinfo',
            name='state',
            field=models.CharField(default='closed', max_length=10, verbose_name='state'),
            preserve_default=False,
        ),
    ]
