# Generated by Django 3.2.5 on 2022-01-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0006_auto_20211016_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='full name'),
        ),
    ]
