# Generated by Django 3.2.5 on 2022-07-13 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0007_alter_repository_full_name'),
        ('contributors', '0007_auto_20220713_2100'),
    ]

    operations = [
    ]
