# Generated by Django 4.2.3 on 2023-09-08 03:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contributors", "0012_alter_contributionlabel_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="label",
            name="name",
            field=models.CharField(max_length=60),
        ),
    ]
