# Generated by Django 4.2.4 on 2023-11-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contributors", "0013_alter_label_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="fork",
            field=models.BooleanField(default=False, verbose_name="fork"),
        ),
    ]
