# Generated by Django 4.0.7 on 2022-11-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('custom_auth', '0003_groupuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='groups',
            field=models.ManyToManyField(to='auth.group'),
        ),
    ]
