# Generated by Django 4.2.11 on 2024-03-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_auth", "0005_alter_siteuser_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteuser",
            name="github_token",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="GitHub token"
            ),
        ),
    ]
